/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs/route'
import { Route as ApiKeysRouteImport } from './routes/api-keys/route'
import { Route as DashboardRouteImport } from './routes/_dashboard/route'
import { Route as LogsIndexImport } from './routes/logs/index'
import { Route as ApiKeysIndexImport } from './routes/api-keys/index'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'

// Create/Update Routes

const LogsRouteRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const ApiKeysRouteRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LogsIndexRoute = LogsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsRouteRoute,
} as any)

const ApiKeysIndexRoute = ApiKeysIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiKeysRouteRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/api-keys/': {
      id: '/api-keys/'
      path: '/'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof ApiKeysIndexImport
      parentRoute: typeof ApiKeysRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexImport
      parentRoute: typeof LogsRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiKeysRouteRouteChildren {
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute
}

const ApiKeysRouteRouteChildren: ApiKeysRouteRouteChildren = {
  ApiKeysIndexRoute: ApiKeysIndexRoute,
}

const ApiKeysRouteRouteWithChildren = ApiKeysRouteRoute._addFileChildren(
  ApiKeysRouteRouteChildren,
)

interface LogsRouteRouteChildren {
  LogsIndexRoute: typeof LogsIndexRoute
}

const LogsRouteRouteChildren: LogsRouteRouteChildren = {
  LogsIndexRoute: LogsIndexRoute,
}

const LogsRouteRouteWithChildren = LogsRouteRoute._addFileChildren(
  LogsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteRouteWithChildren
  '/api-keys': typeof ApiKeysRouteRouteWithChildren
  '/logs': typeof LogsRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/logs/': typeof LogsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/api-keys': typeof ApiKeysIndexRoute
  '/logs': typeof LogsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/api-keys': typeof ApiKeysRouteRouteWithChildren
  '/logs': typeof LogsRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/logs/': typeof LogsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/api-keys' | '/logs' | '/' | '/api-keys/' | '/logs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-keys' | '/logs'
  id:
    | '__root__'
    | '/_dashboard'
    | '/api-keys'
    | '/logs'
    | '/_dashboard/'
    | '/api-keys/'
    | '/logs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiKeysRouteRoute: typeof ApiKeysRouteRouteWithChildren
  LogsRouteRoute: typeof LogsRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiKeysRouteRoute: ApiKeysRouteRouteWithChildren,
  LogsRouteRoute: LogsRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard",
        "/api-keys",
        "/logs"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard/route.tsx",
      "children": [
        "/_dashboard/"
      ]
    },
    "/api-keys": {
      "filePath": "api-keys/route.tsx",
      "children": [
        "/api-keys/"
      ]
    },
    "/logs": {
      "filePath": "logs/route.tsx",
      "children": [
        "/logs/"
      ]
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.tsx",
      "parent": "/_dashboard"
    },
    "/api-keys/": {
      "filePath": "api-keys/index.tsx",
      "parent": "/api-keys"
    },
    "/logs/": {
      "filePath": "logs/index.tsx",
      "parent": "/logs"
    }
  }
}
ROUTE_MANIFEST_END */
